import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAuth } from '../context/AuthContext';
import { 
    ArrowRight, BookOpen, Users, Zap, CheckCircle, Play, 
    Sparkles, Brain, Trophy, MessageSquare, Code, Star,
    ChevronRight, Shield, Clock, Globe
} from 'lucide-react';

export default function LandingPage() {
    const { loginWithGoogle } = useAuth();

    const stats = [
        { value: '50K+', label: 'Active Learners' },
        { value: '10K+', label: 'Courses Created' },
        { value: '1M+', label: 'Lessons Completed' },
        { value: '4.9', label: 'Average Rating' },
    ];

    const features = [
        {
            icon: Brain,
            title: "AI-Powered Learning",
            desc: "Personalized quizzes and notes generated by advanced AI that adapts to your learning style.",
            gradient: "from-violet-500 to-purple-500"
        },
        {
            icon: BookOpen,
            title: "Smart Course Builder",
            desc: "Transform any YouTube playlist into a structured curriculum with progress tracking.",
            gradient: "from-orange-500 to-amber-500"
        },
        {
            icon: MessageSquare,
            title: "AI Tutor Chat",
            desc: "Get instant answers to your questions with our intelligent tutoring assistant.",
            gradient: "from-blue-500 to-cyan-500"
        },
        {
            icon: Code,
            title: "Code Playground",
            desc: "Practice coding with real-time feedback and AI-powered problem solving.",
            gradient: "from-emerald-500 to-green-500"
        },
        {
            icon: Trophy,
            title: "Gamified Progress",
            desc: "Earn XP, unlock achievements, and compete with learners worldwide.",
            gradient: "from-pink-500 to-rose-500"
        },
        {
            icon: Users,
            title: "Social Learning",
            desc: "Connect with peers, share insights, and learn together in communities.",
            gradient: "from-indigo-500 to-blue-500"
        }
    ];

    const testimonials = [
        {
            name: "Sarah Chen",
            role: "Software Engineer",
            image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
            content: "Learnify transformed how I learn new technologies. The AI tutor is like having a personal mentor 24/7.",
            rating: 5
        },
        {
            name: "Alex Rivera",
            role: "Data Scientist",
            image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
            content: "The quiz generation feature is incredible. It helps me retain information so much better than just watching videos.",
            rating: 5
        },
        {
            name: "Priya Patel",
            role: "Product Manager",
            image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
            content: "Finally, a platform that turns scattered YouTube tutorials into organized learning paths. Game changer!",
            rating: 5
        }
    ];

    return (
        <div className="min-h-screen bg-[#0a0a0f] text-white overflow-hidden">
            {/* Animated Background */}
            <div className="fixed inset-0 pointer-events-none">
                <div className="absolute top-0 left-1/4 w-[600px] h-[600px] bg-orange-500/20 rounded-full blur-[150px] animate-pulse" />
                <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-purple-500/20 rounded-full blur-[150px] animate-pulse delay-1000" />
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-blue-500/10 rounded-full blur-[200px]" />
            </div>

            {/* Grid Pattern */}
            <div className="fixed inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:64px_64px] pointer-events-none" />

            {/* Navigation */}
            <nav className="fixed top-0 w-full z-50 bg-[#0a0a0f]/80 backdrop-blur-xl border-b border-white/5">
                <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                    <Link to="/" className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-orange-500 to-amber-500 rounded-xl flex items-center justify-center shadow-lg shadow-orange-500/25">
                            <Sparkles className="w-5 h-5 text-white" />
                        </div>
                        <span className="text-xl font-bold bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">
                            Learnify
                        </span>
                    </Link>
                    <div className="hidden md:flex items-center gap-8">
                        <a href="#features" className="text-sm text-gray-400 hover:text-white transition-colors">Features</a>
                        <a href="#testimonials" className="text-sm text-gray-400 hover:text-white transition-colors">Testimonials</a>
                        <a href="#pricing" className="text-sm text-gray-400 hover:text-white transition-colors">Pricing</a>
                    </div>
                    <div className="flex items-center gap-3">
                        <Link to="/login" className="text-sm font-medium text-gray-300 hover:text-white transition-colors px-4 py-2">
                            Sign In
                        </Link>
                        <Link to="/signup" className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-orange-500 to-amber-500 rounded-full text-sm font-semibold shadow-lg shadow-orange-500/25 hover:shadow-orange-500/40 transition-all hover:scale-105">
                            Get Started <ArrowRight className="w-4 h-4" />
                        </Link>
                    </div>
                </div>
            </nav>

            {/* Hero Section */}
            <section className="relative pt-32 pb-20 lg:pt-44 lg:pb-32">
                <div className="max-w-7xl mx-auto px-6 relative z-10">
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8 }}
                        className="text-center max-w-4xl mx-auto"
                    >
                        {/* Badge */}
                        <motion.div
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            transition={{ delay: 0.2 }}
                            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-orange-500/10 to-amber-500/10 border border-orange-500/20 mb-8"
                        >
                            <Sparkles className="w-4 h-4 text-orange-400" />
                            <span className="text-sm font-medium text-orange-300">AI-Powered Learning Platform</span>
                        </motion.div>

                        {/* Headline */}
                        <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight leading-[1.1] mb-8">
                            Learn smarter with{' '}
                            <span className="relative">
                                <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 via-amber-400 to-orange-500">
                                    AI Tutors
                                </span>
                                <motion.div
                                    className="absolute -bottom-2 left-0 right-0 h-[6px] bg-gradient-to-r from-orange-500/50 to-amber-500/50 blur-sm"
                                    initial={{ scaleX: 0 }}
                                    animate={{ scaleX: 1 }}
                                    transition={{ delay: 0.5, duration: 0.8 }}
                                />
                            </span>
                        </h1>

                        {/* Subheadline */}
                        <p className="text-xl md:text-2xl text-gray-400 max-w-2xl mx-auto mb-12 leading-relaxed">
                            Transform scattered resources into structured courses. Interactive quizzes, smart notes, and personalized learning paths—all powered by advanced AI.
                        </p>

                        {/* CTA Buttons */}
                        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
                            <Link to="/signup" className="group flex items-center gap-2 h-14 px-8 bg-gradient-to-r from-orange-500 to-amber-500 rounded-full text-lg font-semibold shadow-xl shadow-orange-500/25 hover:shadow-orange-500/40 transition-all hover:scale-105">
                                Start Learning Free
                                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                            </Link>
                            <button className="flex items-center gap-3 h-14 px-8 bg-white/5 border border-white/10 rounded-full text-lg font-medium hover:bg-white/10 transition-colors">
                                <div className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center">
                                    <Play className="w-4 h-4 fill-current ml-0.5" />
                                </div>
                                Watch Demo
                            </button>
                        </div>

                        {/* Trust Indicators */}
                        <div className="flex flex-wrap items-center justify-center gap-8 text-gray-500 text-sm">
                            <div className="flex items-center gap-2">
                                <CheckCircle className="w-4 h-4 text-green-500" />
                                <span>No credit card required</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle className="w-4 h-4 text-green-500" />
                                <span>Free forever plan</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle className="w-4 h-4 text-green-500" />
                                <span>Cancel anytime</span>
                            </div>
                        </div>
                    </motion.div>

                    {/* Stats Bar */}
                    <motion.div
                        initial={{ opacity: 0, y: 40 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.4, duration: 0.8 }}
                        className="mt-20 grid grid-cols-2 md:grid-cols-4 gap-px bg-white/5 rounded-2xl overflow-hidden border border-white/5"
                    >
                        {stats.map((stat, idx) => (
                            <div key={idx} className="bg-[#0a0a0f] p-8 text-center">
                                <div className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent mb-2">
                                    {stat.value}
                                </div>
                                <div className="text-sm text-gray-500">{stat.label}</div>
                            </div>
                        ))}
                    </motion.div>
                </div>
            </section>

            {/* Features Section */}
            <section id="features" className="py-24 relative">
                <div className="max-w-7xl mx-auto px-6">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-center mb-16"
                    >
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-semibold uppercase tracking-wider mb-4">
                            Features
                        </div>
                        <h2 className="text-4xl md:text-5xl font-bold mb-6">
                            Everything you need to{' '}
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-amber-400">
                                learn faster
                            </span>
                        </h2>
                        <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                            Powerful tools designed to transform how you consume and retain knowledge.
                        </p>
                    </motion.div>

                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {features.map((feature, idx) => (
                            <motion.div
                                key={idx}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: idx * 0.1 }}
                                className="group relative bg-gradient-to-br from-white/[0.03] to-transparent border border-white/5 rounded-2xl p-8 hover:border-white/10 transition-all duration-500"
                            >
                                <div className={`w-14 h-14 bg-gradient-to-br ${feature.gradient} rounded-xl flex items-center justify-center mb-6 shadow-lg`}>
                                    <feature.icon className="w-7 h-7 text-white" />
                                </div>
                                <h3 className="text-xl font-semibold mb-3 group-hover:text-orange-400 transition-colors">
                                    {feature.title}
                                </h3>
                                <p className="text-gray-400 leading-relaxed">
                                    {feature.desc}
                                </p>
                                <ChevronRight className="absolute top-8 right-8 w-5 h-5 text-gray-600 group-hover:text-orange-400 group-hover:translate-x-1 transition-all opacity-0 group-hover:opacity-100" />
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Testimonials Section */}
            <section id="testimonials" className="py-24 relative">
                <div className="max-w-7xl mx-auto px-6">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-center mb-16"
                    >
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-pink-500/10 border border-pink-500/20 text-pink-400 text-xs font-semibold uppercase tracking-wider mb-4">
                            Testimonials
                        </div>
                        <h2 className="text-4xl md:text-5xl font-bold mb-6">
                            Loved by{' '}
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-amber-400">
                                thousands
                            </span>
                        </h2>
                        <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                            Join a community of learners who are achieving their goals faster.
                        </p>
                    </motion.div>

                    <div className="grid md:grid-cols-3 gap-6">
                        {testimonials.map((testimonial, idx) => (
                            <motion.div
                                key={idx}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: idx * 0.1 }}
                                className="bg-gradient-to-br from-white/[0.03] to-transparent border border-white/5 rounded-2xl p-8"
                            >
                                <div className="flex items-center gap-1 mb-4">
                                    {[...Array(testimonial.rating)].map((_, i) => (
                                        <Star key={i} className="w-4 h-4 fill-amber-400 text-amber-400" />
                                    ))}
                                </div>
                                <p className="text-gray-300 mb-6 leading-relaxed">
                                    "{testimonial.content}"
                                </p>
                                <div className="flex items-center gap-3">
                                    <img 
                                        src={testimonial.image} 
                                        alt={testimonial.name}
                                        className="w-12 h-12 rounded-full object-cover ring-2 ring-white/10"
                                    />
                                    <div>
                                        <div className="font-semibold">{testimonial.name}</div>
                                        <div className="text-sm text-gray-500">{testimonial.role}</div>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="py-24 relative">
                <div className="max-w-5xl mx-auto px-6">
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        viewport={{ once: true }}
                        className="relative bg-gradient-to-br from-orange-500/20 via-amber-500/10 to-purple-500/20 rounded-[2.5rem] p-12 md:p-20 text-center border border-white/10 overflow-hidden"
                    >
                        {/* Glow Effect */}
                        <div className="absolute inset-0 bg-gradient-to-r from-orange-500/10 to-amber-500/10 blur-3xl" />
                        
                        <div className="relative z-10">
                            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 mb-8">
                                <Sparkles className="w-4 h-4 text-orange-400" />
                                <span className="text-sm text-gray-300">Start your journey today</span>
                            </div>
                            
                            <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
                                Ready to accelerate your learning?
                            </h2>
                            <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-10">
                                Join 50,000+ learners who are already mastering new skills faster with Learnify AI.
                            </p>
                            
                            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                                <Link to="/signup" className="group flex items-center gap-2 h-14 px-8 bg-white text-gray-900 rounded-full text-lg font-semibold shadow-xl hover:bg-gray-100 transition-all hover:scale-105">
                                    Get Started Free
                                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                                </Link>
                                <Link to="/login" className="flex items-center gap-2 h-14 px-8 bg-white/5 border border-white/10 rounded-full text-lg font-medium hover:bg-white/10 transition-colors">
                                    Sign In
                                </Link>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* Footer */}
            <footer className="py-12 border-t border-white/5">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                        <div className="flex items-center gap-3">
                            <div className="w-8 h-8 bg-gradient-to-br from-orange-500 to-amber-500 rounded-lg flex items-center justify-center">
                                <Sparkles className="w-4 h-4 text-white" />
                            </div>
                            <span className="font-semibold text-gray-300">Learnify AI</span>
                        </div>
                        <div className="flex items-center gap-6 text-sm text-gray-500">
                            <a href="#" className="hover:text-white transition-colors">Privacy</a>
                            <a href="#" className="hover:text-white transition-colors">Terms</a>
                            <a href="#" className="hover:text-white transition-colors">Support</a>
                        </div>
                        <div className="text-sm text-gray-600">
                            © 2024 Learnify AI. All rights reserved.
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    );
}
